services:
  aeotrade_container:
    image: hub.aeotrade.com/open-source/aeotrade_container:latest
    container_name: aeotrade_container
    restart: unless-stopped
    extra_hosts:
      - "backend:127.0.0.1"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "3001:80"
