services:
  nginx:
    image: hub.aeotrade.com/open-source/nginx:1.28.0
    container_name: nginx
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    environment:
      - TZ=Asia/Shanghai
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
    ports:
      - "80:80"
